### ISSUE TITLE
ESM build not working

### ISSUE THREAD

**Issue by jdpt0** [ka-weihe/fastest-levenshtein#19]
When building with vite, I'm getting this error:

```
[vite-plugin-pwa:build] Failed to resolve entry for package "fastest-levenshtein". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "fastest-levenshtein". The package may have incorrect main/module/exports specified in its package.json.
```

```
"module": "./esm/mod.esm.js",
```

This file does not exist on the published version of fastest-levenshtein:
https://unpkg.com/browse/fastest-levenshtein@1.0.14/

Hence the failure.

**Comment by jdpt0** [comment]
@RoXuS Any ideas on this?

**Comment by chadkirby** [comment]
FWIW, 1.0.13 seems to have a working ESM build

**Comment by RoXuS** [comment]
Hey the following MR should fix this: https://github.com/ka-weihe/fastest-levenshtein/pull/20

**Comment by nelsonjd** [comment]
This might be a dumb question but how is `1.0.13/14` available when the `package.json` in this repo, on master which is the only branch I can see is on `1.0.12` ?

**Comment by RoXuS** [comment]
Correct, but I am not the maintener, I can't fix that ^^

**Comment by ka-weihe** [comment]
Sorry, guys! I will fix this now.

**Comment by ka-weihe** [comment]
I have released a new version. Please let me know if it works now.

**Comment by jdpt0** [comment]
@ka-weihe Thanks for the update. Still seeing the same error, unfortunately. 

I'm still not seeing the file specified in the `package.json` (`"./esm/mod.esm.js"`) on the [latest published version](https://unpkg.com/browse/fastest-levenshtein@1.0.15/esm/). Maybe this file is not mapped correctly? Should it be `"./esm/mod.js"`?

**Comment by ka-weihe** [comment]
I think you're right. I've published a new version. Sorry about this.

**Comment by jdpt0** [comment]
All working now, thanks!
